### ISSUE TITLE
Remove activesupport 6.x from dockerfile

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/shipit#168]
We pinned activesupport to 6.1.5 in https://github.com/rubygems/shipit/pull/167 to work around https://github.com/Shopify/krane/issues/851. It would be nice to move off activesupport 6.1.

**Comment by simi** [comment]
What about https://github.com/Shopify/krane/pull/861? I was able to run krane locally with AS 7.

**Comment by simi** [comment]
At https://shipit.rubygems.org/rubygems/shipit/production/deploys/2038 there was still used old image (using kubernetes-deploy under the hood having also krane command), you have to deploy new image manually to fix the problem if I understand it well.

**Comment by sonalkr132** [comment]
Please feel to free to give it a try by removing the line I added in #167. AFAUI, as per #861 krane is not compatiable with activesupport 7.x.

**Comment by simi** [comment]
fixed by https://github.com/rubygems/shipit/commit/c8e958daf68da5ca674379e0a90456e0d4e4009b
